apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterhm-290b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "clusterhm-290b"
  template:
    metadata:
      labels:
        app: "clusterhm-290b"
    spec:
      containers:
        - name: "clusterhm-290b"
          image: "azeacrhm5.azurecr.io/clusterhm"
          ports:
          - containerPort: 80